POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Jeffery",
    "author": "root",
    "url": "weoigweopgij",
    "likes": 25,
    "userId": "6a4778416345d0e1d7df5eb7"
}